version: 2

sources:
  - name: default
    database: '{{target.catalog}}'
    schema: '{% if target.name == "prod" %}source{% else %}default{% endif %}'
    tables:
      - name: fact_sales
      - name: fact_returns
      - name: dim_customer
      - name: dim_product
      - name: dim_date
      - name: dim_store
  - name: tables
    database: '{{target.catalog}}'
    schema: '{% if target.name == "prod" %}source{% else %}tables{% endif %}'
    tables:
      - name: items